// Plotweaver — каталог вопросов.
//
// Это ЧИСТЫЕ ДАННЫЕ, без единой строчки вёрстки. Экран (ui.js) читает этот
// список и рисует по нему интерфейс — на русском (label/hint). У каждого
// вопроса и варианта есть английский labelEn — он используется в prompt.js
// при сборке текста, который реально уходит модели, а RU hint показывается
// тултипом при наведении на чип (и как краткое описание под заголовком
// вопроса/секции).
//
// Типы вопросов:
//   'single' — чипы, выбрать можно только один (клик по новому снимает старый)
//   'multi'  — чипы, можно выбрать несколько; maxSelect ограничивает сколько
//              именно (если не указан — лимита нет)
//   'text'   — нет пресетов вообще, только свои чипы через "+"
//
// custom: true — рядом с чипами есть кнопка "+ свой".
// Если вопрос пустой (ничего не выбрано) — он просто не попадёт в промт.

export const SECTIONS = [
    {
        id: 'destination',
        title: 'Точка назначения',
        titleEn: 'Destination',
        hint: 'Где и как эта история должна закончиться — или не заканчиваться вовсе.',
        questions: [
            {
                id: 'ending_type',
                label: 'Тип развязки',
                labelEn: 'Ending type',
                hint: 'Нужна ли чёткая точка в конце плана, или можно оставить его открытым.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'closed', label: 'Закрытый финал', labelEn: 'closed ending, everything resolved', hint: 'История доходит до чёткой точки, всё разрешено.' },
                    { id: 'open', label: 'Открытый финал', labelEn: 'open ending, deliberately unresolved', hint: 'Финальная сцена есть, но исход намеренно неясен.' },
                ],
            },
            {
                id: 'ending_point',
                label: 'Конечная точка',
                labelEn: 'Endpoint',
                hint: 'В каком состоянии должны оказаться герои к концу плана — можно выбрать несколько граней сразу.',
                type: 'multi',
                maxSelect: 3,
                custom: true,
                options: [
                    { id: 'together', label: 'Пара вместе', labelEn: 'the couple ends up together', hint: 'Отношения состоялись.' },
                    { id: 'apart', label: 'Пара врозь', labelEn: 'the couple ends up apart', hint: 'Герои расстаются или не сходятся.' },
                    { id: 'tragic', label: 'Трагический финал', labelEn: 'a tragic ending', hint: 'История заканчивается потерей или горем.' },
                    { id: 'wedding', label: 'Свадьба/помолвка', labelEn: 'a wedding or engagement', hint: 'Отношения официально оформлены.' },
                    { id: 'child', label: 'Рождение ребёнка', labelEn: 'the birth of a child', hint: 'В финале появляется ребёнок.' },
                    { id: 'transformation', label: 'Трансформация героя', labelEn: 'a character transformation', hint: 'Персонаж выходит из истории другим человеком.' },
                    { id: 'balance', label: 'Баланс восстановлен', labelEn: 'balance/status quo restored', hint: 'То, что было разрушено во внешнем мире, выровнялось.' },
                    { id: 'new_start', label: 'Новое начало', labelEn: 'a new beginning', hint: 'Герои шагают в новую главу, без конкретики.' },
                ],
            },
        ],
    },
    {
        id: 'genre_world',
        title: 'Жанр и мир',
        titleEn: 'Genre & world',
        hint: 'Общий жанр истории, узнаваемые тропы и то, насколько план вправе отходить от канона.',
        questions: [
            {
                id: 'genre',
                label: 'Жанр',
                labelEn: 'Genre',
                hint: 'На что должна быть похожа история по духу.',
                type: 'multi',
                maxSelect: 5,
                custom: true,
                options: [
                    { id: 'romance', label: 'Романтика', labelEn: 'romance, feelings and relationship front and center', hint: 'В центре чувства и отношения.' },
                    { id: 'drama', label: 'Драма', labelEn: 'drama, big emotions and serious stakes', hint: 'Сильные эмоции, серьёзные конфликты.' },
                    { id: 'angst', label: 'Ангст', labelEn: 'angst, dwelling on pain, longing, and inner suffering', hint: 'Акцент на боли, тоске, страдании персонажей.' },
                    { id: 'fluff', label: 'Флафф', labelEn: 'fluff, warm and cozy, nothing bad will happen', hint: 'Тепло, уют, ничего плохого не случится.' },
                    { id: 'comedy', label: 'Комедия', labelEn: 'comedy, humor and lightness lead the way', hint: 'Юмор и лёгкость на первом плане.' },
                    { id: 'adventure', label: 'Приключения', labelEn: 'adventure, active plot, travel, and risk', hint: 'Активное действие, путешествие, риск.' },
                    { id: 'mystery', label: 'Детектив/интрига', labelEn: 'mystery/intrigue', hint: 'Загадка, которую нужно разгадать.' },
                    { id: 'horror', label: 'Мистика/хоррор', labelEn: 'horror/supernatural', hint: 'Сверхъестественное, страх, напряжение.' },
                    { id: 'epic_fantasy', label: 'Эпик-фэнтези', labelEn: 'epic fantasy, a sweeping magical world with high stakes', hint: 'Масштабный магический мир, высокие ставки.' },
                    { id: 'slice_of_life', label: 'Повседневность', labelEn: 'slice of life, ordinary days without big upheaval', hint: 'Обычная жизнь без крупных потрясений.' },
                    { id: 'hurt_comfort', label: 'Хёрт/комфорт', labelEn: 'hurt/comfort', hint: 'Герой страдает, кто-то рядом его утешает.' },
                    { id: 'hurt_no_comfort', label: 'Хёрт/без комфорта', labelEn: 'hurt/no comfort', hint: 'Страдание без утешения и разрядки.' },
                    { id: 'dead_dove', label: 'Dead Dove', labelEn: 'dead dove (dark themes played straight, not romanticized)', hint: 'Тёмные темы показаны прямо, без романтизации.' },
                    { id: 'tragedy', label: 'Трагедия', labelEn: 'tragedy, heading toward an unavoidable loss', hint: 'История ведёт к неотвратимой потере.' },
                    { id: 'road_story', label: 'Роуд-стори', labelEn: 'road story, the plot unfolds through a journey', hint: 'Сюжет разворачивается в пути, через путешествие.' },
                    { id: 'fantasy', label: 'Фэнтези', labelEn: 'fantasy elements', hint: 'Магия и вымышленный мир как общий элемент поверх любого сеттинга.' },
                    { id: 'fairy_tale', label: 'Сказка/мифология', labelEn: 'fairy tale/mythology', hint: 'Стиль и мотивы народных сказок или мифов.' },
                    { id: 'sci_fi', label: 'Научная фантастика', labelEn: 'science fiction, technology and science shape the world', hint: 'Технологии, наука, будущее как основа мира.' },
                    { id: 'cyberpunk', label: 'Киберпанк', labelEn: 'cyberpunk, high tech, low life, a grim urban world', hint: 'Высокие технологии, мрачный урбанистический мир.' },
                    { id: 'steampunk', label: 'Стимпанк', labelEn: 'steampunk, steam-powered tech, retro-futurism', hint: 'Паровые технологии, ретро-футуризм.' },
                    { id: 'post_apocalyptic', label: 'Постапокалипсис', labelEn: 'post-apocalyptic, survival among the ruins of a fallen world', hint: 'Мир после катастрофы, выживание среди руин.' },
                    { id: 'military', label: 'Военное', labelEn: 'military, army life and combat as the backdrop', hint: 'Армия, боевые действия, фронт.' },
                    { id: 'crime', label: 'Криминал/мафия', labelEn: 'crime/mafia', hint: 'Преступный мир, бандитские структуры.' },
                    { id: 'court_intrigue', label: 'Придворные интриги', labelEn: 'court intrigue', hint: 'Борьба за власть, заговоры при дворе.' },
                    { id: 'academy', label: 'Академия/учёба', labelEn: 'academy/school setting', hint: 'События разворачиваются в школе/университете/академии.' },
                    { id: 'sports', label: 'Спорт', labelEn: 'sports, competition, training, and team stakes', hint: 'Соревнования, тренировки, командная борьба.' },
                    { id: 'superhero', label: 'Супергероика', labelEn: 'superhero, powers and their own mythology around the cast', hint: 'Герои со сверхспособностями и своя мифология вокруг них.' },
                    { id: 'erotica', label: 'Эротика', labelEn: 'erotica, sensuality and sexuality as the genre itself', hint: 'Чувственность и сексуальность как жанровая основа.' },
                    { id: 'smut', label: 'Смут', labelEn: 'smut, explicit scenes as a meaningful part of the story', hint: 'Откровенные сцены как значимая часть истории.' },
                    { id: 'pwp', label: 'PWP', labelEn: 'PWP (plot secondary, focus on the intimate scene itself)', hint: 'Сюжет вторичен, в фокусе сама сцена близости.' },
                ],
            },
            {
                id: 'genre_tropes',
                label: 'Жанровые тропы',
                labelEn: 'Genre tropes',
                hint: 'Конкретные сюжетные приёмы, которые план должен задействовать.',
                type: 'multi',
                maxSelect: 5,
                custom: true,
                options: [
                    { id: 'one_bed', label: 'Только одна кровать', labelEn: 'only one bed trope', hint: 'Герои вынуждены делить одну постель.' },
                    { id: 'forced_proximity', label: 'Вынужденная близость', labelEn: 'forced proximity', hint: 'Обстоятельства держат героев рядом друг с другом.' },
                    { id: 'locked_in', label: 'Заперты вместе', labelEn: 'locked in together', hint: 'Герои физически не могут разойтись (шторм, поломка, ловушка).' },
                    { id: 'false_identity', label: 'Ложная личность', labelEn: 'false identity, a character passing themselves off as someone else', hint: 'Герой выдаёт себя за другого.' },
                    { id: 'identity_reveal', label: 'Раскрытие личности', labelEn: 'identity reveal, the truth about who someone really is comes out', hint: 'Правда о том, кто есть кто, вскрывается по ходу истории.' },
                    { id: 'mistaken_identity', label: 'Ошибочная идентификация', labelEn: 'mistaken identity, a character is taken for someone else', hint: 'Героя принимают не за того, кто он есть.' },
                    { id: 'secret_heir', label: 'Тайный наследник', labelEn: 'secret heir, a hidden claimant to a title, throne, or bloodline', hint: 'Персонаж — скрытый претендент на статус/трон/род.' },
                    { id: 'undercover', label: 'Под прикрытием', labelEn: "undercover, acting while hiding one's true role or mission", hint: 'Герой действует, скрывая истинную роль или задание.' },
                    { id: 'amnesia', label: 'Амнезия', labelEn: 'amnesia, a character has lost their memory', hint: 'Персонаж теряет память.' },
                    { id: 'curse', label: 'Проклятие', labelEn: 'a curse laid on a character or the world', hint: 'На герое или мире лежит магическое проклятие.' },
                    { id: 'prophecy', label: 'Пророчество', labelEn: 'a prophecy shapes the characters\' fate', hint: 'Судьбу героев определяет предсказание.' },
                    { id: 'chosen_one', label: 'Избранный', labelEn: 'chosen one, destined for something great', hint: 'Герой — тот самый, кому суждено нечто великое.' },
                    { id: 'time_travel', label: 'Путешествие во времени', labelEn: 'time travel between eras', hint: 'Герои перемещаются между эпохами.' },
                    { id: 'time_loop', label: 'Временная петля', labelEn: 'time loop, the same events repeat over and over', hint: 'Одни и те же события повторяются снова и снова.' },
                    { id: 'reincarnation', label: 'Реинкарнация', labelEn: 'reincarnation, a character reborn into a new life', hint: 'Персонаж переродился в новой жизни.' },
                    { id: 'body_swap', label: 'Обмен телами', labelEn: 'body swap between characters', hint: 'Герои меняются телами друг с другом.' },
                    { id: 'betrayal', label: 'Предательство', labelEn: 'betrayal by someone close', hint: 'Кто-то из близких предаёт доверие.' },
                    { id: 'trust_issues', label: 'Проблемы с доверием', labelEn: "trust issues, the characters can't fully believe each other", hint: 'Герои не могут до конца поверить друг другу.' },
                    { id: 'miscommunication', label: 'Недопонимание', labelEn: 'miscommunication driving the conflict, things left unsaid or misread', hint: 'Конфликт растёт из непонятого/невысказанного.' },
                    { id: 'redemption', label: 'Искупление', labelEn: 'a redemption arc, trying to make up for past wrongs', hint: 'Герой пытается загладить прошлую вину.' },
                    { id: 'revenge', label: 'Месть', labelEn: 'revenge drives the plot', hint: 'Сюжет движим желанием отомстить.' },
                    { id: 'found_family', label: 'Обретённая семья', labelEn: 'found family, chosen bonds standing in for blood family', hint: 'Герои создают семью не по крови, а по выбору.' },
                    { id: 'captivity', label: 'Плен', labelEn: 'captivity, a character held against their will', hint: 'Персонаж удерживается против воли.' },
                    { id: 'kidnapping', label: 'Похищение', labelEn: 'a kidnapping', hint: 'Героя похищают.' },
                    { id: 'rescue', label: 'Спасение', labelEn: 'a rescue', hint: 'Один герой физически выручает другого из беды.' },
                    { id: 'sacrifice', label: 'Жертва', labelEn: 'self-sacrifice for someone or something', hint: 'Герой готов на самопожертвование ради другого/цели.' },
                    { id: 'faked_death', label: 'Инсценированная смерть', labelEn: 'a faked death, staged rather than real', hint: 'Смерть персонажа оказывается постановкой.' },
                    { id: 'resurrection', label: 'Воскрешение', labelEn: 'resurrection, a character returns from the dead', hint: 'Персонаж возвращается из мёртвых.' },
                    { id: 'deal_with_devil', label: 'Сделка с дьяволом', labelEn: 'a dangerous bargain struck to get what they want', hint: 'Герой заключает опасную сделку ради цели.' },
                    { id: 'loyalty_test', label: 'Испытание верности', labelEn: 'a test of loyalty', hint: 'Героя проверяют на преданность.' },
                    { id: 'secret_pregnancy', label: 'Тайная беременность', labelEn: 'a pregnancy kept secret from someone important', hint: 'Беременность скрывается от кого-то важного.' },
                    { id: 'investigation', label: 'Расследование', labelEn: 'an investigation into a mystery or crime', hint: 'Герои распутывают тайну или преступление.' },
                    { id: 'heist', label: 'Ограбление', labelEn: 'a heist built around a theft or raid', hint: 'Сюжет строится вокруг кражи/налёта.' },
                    { id: 'tournament', label: 'Турнир', labelEn: 'a tournament with clear rules and stakes', hint: 'Состязание с чёткими правилами и ставками.' },
                    { id: 'war', label: 'Война', labelEn: 'a large-scale war as backdrop or driving force', hint: 'Крупный вооружённый конфликт как фон или движущая сила.' },
                    { id: 'fish_out_of_water', label: 'Не в своей тарелке', labelEn: 'fish out of water, a character in an unfamiliar role or setting', hint: 'Герой оказывается в непривычной для себя роли/среде.' },
                    { id: 'five_plus_one', label: '5+1', labelEn: '5+1 structure (five failed/varied attempts, then one that succeeds)', hint: 'Пять неудачных/разных попыток и одна удавшаяся.' },
                ],
            },
            {
                id: 'au',
                label: 'AU',
                labelEn: 'AU (alternate universe)',
                hint: 'Можно перенести этих же персонажей в совершенно другой сеттинг, оставив карточку/персону как есть — или остаться в каноне.',
                type: 'multi',
                maxSelect: 3,
                custom: true,
                options: [
                    { id: 'canon', label: 'Канон', labelEn: 'canon setting, no AU', hint: 'Мир и роли остаются как в карточке/лорбуке.' },
                    { id: 'coffee_shop', label: 'Кофейня', labelEn: 'coffee shop AU', hint: 'Герои встречаются/работают в кофейне.' },
                    { id: 'university', label: 'Университет/колледж', labelEn: 'university AU', hint: 'Студенческая жизнь.' },
                    { id: 'school', label: 'Школа', labelEn: 'school AU', hint: 'Школьная среда.' },
                    { id: 'modern', label: 'Современный мир', labelEn: 'modern-day AU', hint: 'История перенесена в наши дни.' },
                    { id: 'historical', label: 'Историческая эпоха', labelEn: 'historical-era AU', hint: 'Герои перенесены в прошлое.' },
                    { id: 'royal_court', label: 'Королевский двор', labelEn: 'royalty AU', hint: 'Герои в роли монаршей семьи/двора.' },
                    { id: 'office', label: 'Офис/корпорация', labelEn: 'office AU', hint: 'Корпоративная среда, коллеги.' },
                    { id: 'band', label: 'Музыкальная группа/индустрия', labelEn: 'band/music industry AU', hint: 'Герои в мире музыки/шоу-бизнеса.' },
                    { id: 'no_powers', label: 'Без сил/способностей', labelEn: 'no-powers AU', hint: 'Магия/сверхспособности убраны из мира.' },
                    { id: 'superhero_au', label: 'Супергероика', labelEn: 'superhero AU', hint: 'Герои получают сверхспособности.' },
                    { id: 'human', label: 'Люди', labelEn: 'human AU', hint: 'Нечеловеческие персонажи становятся людьми.' },
                    { id: 'apocalypse', label: 'Апокалипсис/зомби', labelEn: 'apocalypse/zombie AU', hint: 'Мир после катастрофы/зомби-нашествия.' },
                    { id: 'mermaid', label: 'Русалки', labelEn: 'mermaid AU', hint: 'Герои — морской народ.' },
                    { id: 'vampire', label: 'Вампиры', labelEn: 'vampire AU', hint: 'Герои — вампиры.' },
                    { id: 'werewolf', label: 'Оборотни', labelEn: 'werewolf AU', hint: 'Герои — оборотни.' },
                    { id: 'cyberpunk_au', label: 'Киберпанк', labelEn: 'cyberpunk AU', hint: 'Высокотехнологичный мрачный мир.' },
                    { id: 'omegaverse', label: 'Омегаверс', labelEn: 'omegaverse AU', hint: 'Мир с альфа/бета/омега-динамикой.' },
                ],
            },
            {
                id: 'world_role',
                label: 'Роль мира',
                labelEn: 'Role of the world',
                hint: 'Насколько сильно мир вокруг влияет на сюжет.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'drives_plot', label: 'Двигает сюжет', labelEn: 'actively drives the plot', hint: 'События мира активно влияют на историю.' },
                    { id: 'present_not_focus', label: 'Присутствует, но не в фокусе', labelEn: 'present but not the focus', hint: 'Мир заметен, но в центре — отношения.' },
                    { id: 'background', label: 'Просто фон', labelEn: 'pure background', hint: 'Мир практически не влияет на сюжет.' },
                ],
            },
        ],
    },
    {
        id: 'conflict',
        title: 'Конфликт',
        titleEn: 'Conflict',
        hint: 'Что создаёт напряжение в истории и толкает сюжет вперёд.',
        questions: [
            {
                id: 'conflict_type',
                label: 'Тип конфликта',
                labelEn: 'Conflict type',
                hint: 'Откуда берётся главное напряжение — извне, изнутри героев, или и то, и другое.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'external', label: 'Внешний', labelEn: 'external', hint: 'Конфликт идёт извне — враги, обстоятельства.' },
                    { id: 'internal', label: 'Внутренний', labelEn: 'internal', hint: 'Конфликт внутри самих героев — страхи, сомнения.' },
                    { id: 'both', label: 'Внешний и внутренний', labelEn: 'both external and internal', hint: 'Работают оба уровня сразу.' },
                    { id: 'none', label: 'Без конфликта', labelEn: 'no conflict', hint: 'Slice-of-life без противостояния.' },
                ],
            },
            {
                id: 'conflict_source',
                label: 'Источник конфликта',
                labelEn: 'Conflict source',
                hint: 'Опиши своими словами, в чём суть конфликта — это может быть как конкретный персонаж, так и обстоятельства, случайность, само устройство мира (необязательно).',
                type: 'text',
                custom: true,
            },
            {
                id: 'antagonist',
                label: 'Антагонист',
                labelEn: 'Antagonist',
                hint: 'Есть ли у конфликта конкретное лицо, которое ему противостоит.',
                type: 'single',
                custom: true,
                options: [
                    { id: 'figure', label: 'Конкретная фигура', labelEn: 'a specific figure', hint: 'У конфликта есть лицо.' },
                    { id: 'circumstances', label: 'Обстоятельства без лица', labelEn: 'faceless circumstances', hint: 'Противостояние безличное.' },
                    { id: 'none', label: 'Нет антагониста', labelEn: 'no antagonist', hint: 'Никто конкретно не противостоит героям.' },
                    { id: 'model_choice', label: 'На усмотрение модели', labelEn: "model's choice", hint: 'Пусть модель решит сама.' },
                ],
            },
            {
                id: 'plot_twists',
                label: 'Плоттвисты',
                labelEn: 'Plot twists',
                hint: 'Насколько часто и резко сюжет должен сворачивать в неожиданную сторону.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'minimal', label: 'Минимум', labelEn: 'minimal', hint: 'Почти без неожиданных поворотов.' },
                    { id: 'moderate', label: 'Умеренно', labelEn: 'moderate', hint: 'Пара заметных поворотов по ходу истории.' },
                    { id: 'plenty', label: 'Много и смело', labelEn: 'plenty and bold', hint: 'Сюжет активно удивляет.' },
                ],
            },
        ],
    },
    {
        id: 'romance',
        title: 'Романтика',
        titleEn: 'Romance',
        hint: 'Динамика отношений между персонажами и то, как они будут развиваться дальше.',
        questions: [
            {
                id: 'relationship_now',
                label: 'Тип отношений сейчас',
                labelEn: 'Current relationship type',
                hint: 'Какими персонажи входят в эту историю прямо сейчас, на старте плана.',
                type: 'single',
                custom: true,
                options: [
                    { id: 'strangers', label: 'Не знакомы', labelEn: 'strangers', hint: 'Ещё не встречались.' },
                    { id: 'friends', label: 'Друзья', labelEn: 'friends', hint: 'Дружеские отношения.' },
                    { id: 'rivals', label: 'Враги/соперники', labelEn: 'enemies/rivals', hint: 'Противостояние.' },
                    { id: 'fwb', label: 'С бонусом', labelEn: 'friends with benefits', hint: 'Дружба плюс физическая близость.' },
                    { id: 'couple', label: 'Уже пара', labelEn: 'already a couple', hint: 'Отношения официально начаты.' },
                    { id: 'exes', label: 'Бывшие', labelEn: 'exes', hint: 'Отношения уже закончились раньше.' },
                    { id: 'complicated', label: 'Всё сложно', labelEn: "it's complicated", hint: 'Статус неоднозначный — пусть модель сама разберётся по контексту.' },
                ],
            },
            {
                id: 'relationship_trope',
                label: 'Троп отношений',
                labelEn: 'Relationship trope',
                hint: 'Какая динамика должна лежать в основе развития отношений — можно выбрать несколько.',
                type: 'multi',
                maxSelect: 5,
                custom: true,
                options: [
                    { id: 'enemies_to_lovers', label: 'Из врагов в любовники', labelEn: 'enemies to lovers', hint: 'Начинали как противники.' },
                    { id: 'friends_to_lovers', label: 'Из друзей в любовники', labelEn: 'friends to lovers', hint: 'Дружба перерастает в романтику.' },
                    { id: 'lovers_to_enemies', label: 'Из любовников во враги', labelEn: 'lovers to enemies', hint: 'Отношения разрушаются в противостояние.' },
                    { id: 'hate_to_love', label: 'Ненависть в любовь', labelEn: 'hate to love, strong dislike turns into feelings', hint: 'Сильная неприязнь оборачивается чувствами.' },
                    { id: 'slow_burn_trope', label: 'Слоуберн', labelEn: 'slow burn', hint: 'Чувства нарастают очень постепенно.' },
                    { id: 'mutual_pining', label: 'Взаимное томление', labelEn: 'mutual pining', hint: 'Оба влюблены, но молчат об этом.' },
                    { id: 'unrequited_love', label: 'Безответная любовь', labelEn: "unrequited love, feelings that aren't (yet) returned", hint: 'Чувства не взаимны (пока).' },
                    { id: 'forbidden_love', label: 'Запретная любовь', labelEn: 'forbidden love, the relationship is off-limits for some reason', hint: 'Отношения под запретом по каким-то причинам.' },
                    { id: 'second_chance', label: 'Второй шанс', labelEn: 'second chance romance, giving the relationship another try', hint: 'Герои дают отношениям ещё одну попытку.' },
                    { id: 'love_triangle', label: 'Любовный треугольник', labelEn: 'a love triangle, a third party in the mix', hint: 'В игре участвует третий.' },
                    { id: 'age_gap', label: 'Разница в возрасте', labelEn: 'a noticeable age gap between the characters', hint: 'Заметная разница в возрасте между героями.' },
                    { id: 'opposites_attract', label: 'Противоположности', labelEn: 'opposites attract, very different personalities', hint: 'Герои по характеру очень разные.' },
                    { id: 'grumpy_sunshine', label: 'Ворчун и солнышко', labelEn: 'grumpy x sunshine', hint: 'Один мрачный и колючий, другой светлый и тёплый.' },
                    { id: 'true_mates', label: 'Истинная пара', labelEn: 'true mates/soulmates (setting-bound bond)', hint: 'Связь предопределена самим миром.' },
                    { id: 'soulmates', label: 'Соулмейты', labelEn: 'soulmates, destined for each other', hint: 'Судьбой предназначены друг другу.' },
                    { id: 'fake_relationship', label: 'Фиктивные отношения', labelEn: 'a fake relationship that becomes real', hint: 'Отношения понарошку, которые становятся настоящими.' },
                    { id: 'secret_relationship', label: 'Тайные отношения', labelEn: 'a secret relationship hidden from others', hint: 'Отношения скрываются от окружающих.' },
                    { id: 'arranged_marriage', label: 'Брак по расчёту', labelEn: 'an arranged marriage, not made for love', hint: 'Союз заключён не по любви.' },
                    { id: 'marriage_first', label: 'Сначала брак — потом любовь', labelEn: 'married first, love later', hint: 'Чувства приходят уже после свадьбы.' },
                    { id: 'friends_with_benefits_trope', label: 'Друзья с бонусом', labelEn: 'friends with benefits', hint: 'Физическая близость без обязательств, которая перерастает в большее.' },
                    { id: 'one_night_stand', label: 'Одна ночь', labelEn: 'one night stand that grows into more', hint: 'Начинается со случайной встречи.' },
                    { id: 'exes_reunited', label: 'Бывшие снова вместе', labelEn: 'exes reunited', hint: 'Бывшие пара находят друг друга снова.' },
                    { id: 'childhood_friends', label: 'Друзья детства', labelEn: 'childhood friends to lovers, known each other since childhood', hint: 'Знакомы с самого детства.' },
                    { id: 'roommates', label: 'Соседи по квартире', labelEn: 'roommates to lovers', hint: 'Живут под одной крышей.' },
                    { id: 'boss_employee', label: 'Начальник и подчинённый', labelEn: 'boss/employee, a workplace hierarchy between them', hint: 'Иерархия на работе.' },
                    { id: 'mentor_student', label: 'Наставник и ученик', labelEn: 'mentor/student, one teaches, the other learns', hint: 'Один учит, другой учится.' },
                    { id: 'bodyguard', label: 'Телохранитель', labelEn: 'bodyguard romance', hint: 'Один защищает другого по долгу службы.' },
                ],
            },
            {
                id: 'pace',
                label: 'Темп',
                labelEn: 'Pace',
                hint: 'Насколько быстро персонажи должны сближаться.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'slow_burn', label: 'Медленно', labelEn: 'slow burn pace', hint: 'Сближение растянуто, шаг за шагом.' },
                    { id: 'moderate', label: 'Умеренный', labelEn: 'moderate pace', hint: 'Средний темп сближения.' },
                    { id: 'fast', label: 'Быстрый', labelEn: 'fast pace', hint: 'Сближение происходит быстро.' },
                ],
            },
            {
                id: 'intimacy_tool',
                label: 'Инструмент роста близости',
                labelEn: 'Intimacy-building tool',
                hint: 'Через что в первую очередь раскрывается близость между героями — можно выбрать несколько.',
                type: 'multi',
                maxSelect: 3,
                custom: true,
                options: [
                    { id: 'talks', label: 'Разговоры по душам', labelEn: 'heart-to-heart talks', hint: 'Близость через откровенные разговоры.' },
                    { id: 'daily_life', label: 'Совместный быт', labelEn: 'shared daily life', hint: 'Близость через повседневную рутину вдвоём.' },
                    { id: 'crisis', label: 'Кризис', labelEn: 'a shared crisis', hint: 'Близость закаляется под внешним давлением/угрозой.' },
                    { id: 'rescue', label: 'Спасение', labelEn: 'one rescuing the other', hint: 'Один физически выручает другого.' },
                    { id: 'care', label: 'Забота о раненом/больном', labelEn: 'caring for the sick or injured', hint: 'Близость через уход и заботу.' },
                    { id: 'jealousy', label: 'Ревность', labelEn: 'jealousy', hint: 'Близость обнажается через ревность.' },
                    { id: 'silent_closeness', label: 'Молчаливая близость', labelEn: 'silent closeness (through gestures, not words)', hint: 'Сближение без слов, через жесты и присутствие.' },
                    { id: 'model_choice', label: 'На усмотрение модели', labelEn: "model's choice", hint: 'Пусть модель решит сама.' },
                ],
            },
            {
                id: 'sex',
                label: 'Секс',
                labelEn: 'Sex',
                hint: 'Нужны ли в плане сексуальные сцены и как часто.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'none', label: 'Не нужен', labelEn: 'not needed', hint: 'Без сексуальных сцен.' },
                    { id: 'once', label: 'Один раз, ключевая сцена', labelEn: 'once, as a key scene', hint: 'Одна значимая сцена.' },
                    { id: 'regular', label: 'Регулярно по ходу', labelEn: 'regularly throughout', hint: 'Несколько сцен по ходу плана.' },
                ],
            },
        ],
    },
    {
        id: 'tone',
        title: 'Тон',
        titleEn: 'Tone',
        hint: 'Общее настроение истории и темп, с которым идут события.',
        questions: [
            {
                id: 'vibe',
                label: 'Вайб',
                labelEn: 'Overall vibe',
                hint: 'Какое чувство должно преобладать в истории — можно выбрать основной тон и оттенок.',
                type: 'multi',
                maxSelect: 2,
                custom: false,
                options: [
                    { id: 'warm', label: 'Тепло и уют', labelEn: 'warm and cozy', hint: 'Мягкое, домашнее настроение.' },
                    { id: 'dramatic', label: 'Драма и надрыв', labelEn: 'drama and heartache', hint: 'Эмоциональные всплески и разрывы.' },
                    { id: 'light', label: 'Юмор и лёгкость', labelEn: 'humor and lightness', hint: 'Ничего не давит, легко и смешно.' },
                    { id: 'tense', label: 'Напряжение и тревога', labelEn: 'tension and unease', hint: 'Саспенс, ожидание удара.' },
                    { id: 'melancholic', label: 'Меланхолия', labelEn: 'melancholy, quiet sadness and reflection', hint: 'Тихая грусть, задумчивость.' },
                    { id: 'dark_heavy', label: 'Мрачно и тяжело', labelEn: 'dark and heavy', hint: 'Давящая, безысходная атмосфера.' },
                    { id: 'tender', label: 'Нежность и трепет', labelEn: 'tenderness and quiet awe', hint: 'Бережное, трепетное чувство.' },
                    { id: 'passionate', label: 'Страсть и жар', labelEn: 'passion and heat', hint: 'Интенсивное физическое влечение.' },
                    { id: 'bittersweet', label: 'Горько-сладко', labelEn: 'bittersweet', hint: 'Хорошо, но с привкусом потери.' },
                    { id: 'longing', label: 'Тоска и томление', labelEn: 'longing and yearning', hint: 'Ноющее желание того, чего пока нет.' },
                    { id: 'playful', label: 'Игриво и дерзко', labelEn: 'playful and cheeky', hint: 'Лёгкий флирт, поддразнивание.' },
                    { id: 'epic', label: 'Эпично и торжественно', labelEn: 'epic and grand, weight and ceremony to the moment', hint: 'Масштаб, пафос, значимость момента.' },
                    { id: 'eerie', label: 'Тревожно и жутко', labelEn: 'eerie and unsettling', hint: 'Жуть, паранойя, ощущение угрозы.' },
                    { id: 'contemplative', label: 'Спокойно и созерцательно', labelEn: 'calm and contemplative', hint: 'Медленное, вдумчивое настроение.' },
                    { id: 'chaotic', label: 'Хаотично и абсурдно', labelEn: 'chaotic and absurd', hint: 'Сумбур, нелепость, комедия положений.' },
                ],
            },
            {
                id: 'event_pace',
                label: 'Темп событий',
                labelEn: 'Pace of events',
                hint: 'Насколько плотно события должны идти друг за другом.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'slow', label: 'Медленный', labelEn: 'slow', hint: 'Неспешное развитие событий.' },
                    { id: 'medium', label: 'Средний', labelEn: 'medium', hint: 'Сбалансированный темп.' },
                    { id: 'dense', label: 'Плотный', labelEn: 'dense', hint: 'Событий много и часто.' },
                ],
            },
            {
                id: 'fillers',
                label: 'Филлеры',
                labelEn: 'Filler moments',
                hint: 'Нужны ли спокойные бытовые сцены-передышки между важными событиями.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'none', label: 'Не нужны', labelEn: 'not needed', hint: 'Только значимые события.' },
                    { id: 'some', label: 'Немного для дыхания', labelEn: 'a few, for breathing room', hint: 'Пара спокойных сцен между важными.' },
                    { id: 'plenty', label: 'Много, любим быт', labelEn: 'plenty, we love slice-of-life moments', hint: 'Много бытовых сцен-передышек.' },
                ],
            },
        ],
    },
    {
        id: 'structure',
        title: 'Структура',
        titleEn: 'Structure',
        hint: 'Сколько сюжетных линий вести одновременно и как двигается время между сценами.',
        questions: [
            {
                id: 'storylines',
                label: 'Сюжетные линии',
                labelEn: 'Storylines',
                hint: 'Одна линия (романтика) или несколько параллельных сюжетов сразу.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'romance_only', label: 'Только романтика', labelEn: 'romance only', hint: 'Одна сюжетная линия.' },
                    { id: 'romance_intrigue', label: 'Романтика + интрига', labelEn: 'romance + external intrigue', hint: 'Романтика плюс внешний конфликт.' },
                    { id: 'multiple', label: 'Несколько подсюжетов', labelEn: 'several parallel subplots', hint: 'Несколько параллельных линий.' },
                ],
            },
            {
                id: 'timeline_pace',
                label: 'Темп времени',
                labelEn: 'Timeline pace',
                hint: 'Идёт ли время сцена за сценой, или между сценами можно перескакивать вперёд.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'linear', label: 'Линейно', labelEn: 'linear, day by day', hint: 'Без пропусков во времени.' },
                    { id: 'timeskips', label: 'Скачками/таймскипы', labelEn: 'time skips between scenes', hint: 'Между сценами проходит время.' },
                    { id: 'any', label: 'Неважно', labelEn: "doesn't matter, whatever fits", hint: 'Пусть модель решит сама.' },
                ],
            },
        ],
    },
    {
        id: 'characters',
        title: 'Персонажи',
        titleEn: 'Characters',
        hint: 'Насколько активно в истории участвуют персонажи помимо главной пары.',
        questions: [
            {
                id: 'side_characters',
                label: 'Второстепенные из лорбука',
                labelEn: 'Side characters from the lorebook',
                hint: 'Роль персонажей из лорбука/карточки в развитии сюжета.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'active', label: 'Активно участвуют', labelEn: 'actively involved in the plot', hint: 'Активно участвуют в событиях.' },
                    { id: 'background', label: 'Только фоном', labelEn: 'background presence only', hint: 'Упоминаются, но не в фокусе.' },
                    { id: 'none', label: 'Не участвуют', labelEn: 'not involved', hint: 'Не появляются в плане.' },
                ],
            },
            {
                id: 'new_characters',
                label: 'Новые персонажи',
                labelEn: 'New characters',
                hint: 'Можно ли вводить персонажей, которых нет в карточке/лорбуке.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'free', label: 'Можно свободно', labelEn: 'freely allowed to invent new ones', hint: 'Можно придумывать новых персонажей.' },
                    { id: 'episodic', label: 'Только эпизодично', labelEn: 'only minor, episodic ones', hint: 'Только мелкие, проходные персонажи.' },
                    { id: 'none', label: 'Нет, только имеющиеся', labelEn: 'no, only existing characters', hint: 'Только те, что уже есть.' },
                ],
            },
        ],
    },
    {
        id: 'constraints',
        title: 'Обязательное и запрещённое',
        titleEn: 'Required & forbidden',
        hint: 'То, что обязательно должно случиться в плане, и то, чего в нём быть не должно.',
        questions: [
            {
                id: 'must_scenes',
                label: 'Обязательные сцены/моменты',
                labelEn: 'Must-have scenes/moments',
                hint: 'Конкретные сцены или повороты, которые ты точно хочешь увидеть — добавляй по одному.',
                type: 'text',
                custom: true,
            },
            {
                id: 'avoid',
                label: 'Что избегать',
                labelEn: 'What to avoid',
                hint: 'Темы, повороты или тропы, которые план должен обойти стороной.',
                type: 'text',
                custom: true,
            },
        ],
    },
    {
        id: 'generation',
        title: 'Настройки генерации',
        titleEn: 'Generation settings',
        hint: 'Технические настройки самого запроса к модели — не про сюжет, а про то, как его писать.',
        questions: [
            {
                id: 'invention',
                label: 'Сколько выдумывать',
                labelEn: 'How much to invent',
                hint: 'Насколько свободно модель может додумывать то, чего нет в карточке/лорбуке/истории.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'canon', label: 'Строго канон', labelEn: 'strict canon', hint: 'Только то, что уже установлено.' },
                    { id: 'balanced', label: 'Средне', labelEn: 'balanced', hint: 'Опирается на канон, но может дополнять.' },
                    { id: 'free', label: 'Смело', labelEn: 'bold', hint: 'Свободно додумывает недостающее.' },
                ],
            },
            {
                id: 'format',
                label: 'Формат',
                labelEn: 'Format',
                hint: 'Насколько большой план нужен — от пары вариантов продолжения до многотомной саги.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'nudge', label: 'Толчок', labelEn: 'nudge', hint: '3 варианта продолжения, без арок.' },
                    { id: 'arc', label: 'Арка', labelEn: 'arc', hint: 'Одна арка с несколькими сценами.' },
                    { id: 'volume', label: 'Том', labelEn: 'volume', hint: 'Один том из нескольких арок.' },
                    { id: 'saga', label: 'Сага', labelEn: 'saga', hint: 'Многотомный масштабный план.' },
                ],
            },
            {
                id: 'output_language',
                label: 'Язык генерации',
                labelEn: 'Generation language',
                hint: 'На каком языке модель должна написать сам план.',
                type: 'single',
                custom: false,
                options: [
                    { id: 'ru', label: 'Русский', labelEn: 'Russian', hint: 'План на русском.' },
                    { id: 'en', label: 'English', labelEn: 'English', hint: 'План на английском.' },
                ],
            },
        ],
    },
];

/**
 * Найти вопрос по его id, перебрав все секции.
 * Пригодится в ui.js, чтобы по клику на чип понять,
 * какого типа вопрос (single/multi) и какой у него лимит выбора.
 */
export function findQuestion(questionId) {
    for (const section of SECTIONS) {
        const found = section.questions.find((q) => q.id === questionId);
        if (found) return found;
    }
    return null;
}
